//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.0.2.0")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.2-make-build-project.0+Branch.feature-make-build-project.Sha.675abc621d13e79990e9806231d975b95066497e")]